import type { Metadata } from "next";
import "./globals.css";
import { layoutProps } from "@/types";
import { cn } from "@/lib/utils";
import { inter } from "@/components/fonts";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({ children }: Readonly<layoutProps>) {
  return (
    <html lang="en" className={cn(inter.className)}>
      <body>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
